<script setup lang="ts">
import type { MailboxSummary,SystemStatus,ViewName } from '../types'
defineProps<{system?:SystemStatus;mailboxes:readonly MailboxSummary[]}>()
const emit=defineEmits<{navigate:[view:ViewName]}>()
</script>
<template>
  <section class="metrics"><article><span>Mailboxes</span><strong>{{ system?.mailboxes??0 }}</strong></article><article><span>Unread</span><strong>{{ system?.messages.unread??0 }}</strong></article><article><span>Claimed</span><strong>{{ system?.messages.claimed??0 }}</strong></article><article><span>Acknowledged</span><strong>{{ system?.messages.acknowledged??0 }}</strong></article></section>
  <section class="grid"><article class="panel"><p class="eyebrow">LOCAL AGENT HANDOFF</p><h3>One durable mailbox between agents</h3><pre>Claude Code → Relay One → Codex</pre><ol><li>Create an API key.</li><li>Install MCP from Integrations.</li><li>Let each agent choose, claim, and acknowledge mailbox work.</li></ol><div class="actions"><button @click="emit('navigate','keys')">Create agent key</button><button class="secondary" @click="emit('navigate','integrations')">Connect an agent</button></div></article><article class="panel"><div class="heading"><div><p class="eyebrow">MAILBOXES</p><h3>Current activity</h3></div><button class="link" @click="emit('navigate','mailboxes')">Inspect</button></div><ul><li v-for="mailbox in mailboxes.slice(0,6)" :key="mailbox.name"><code>{{ mailbox.name }}</code><span>{{ mailbox.unread }} unread</span></li><li v-if="!mailboxes.length" class="empty">A mailbox appears when its first message is accepted.</li></ul></article></section>
</template>
<style scoped>.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:18px}.metrics article,.panel{padding:18px;border:1px solid var(--border);border-radius:12px;background:var(--surface)}.metrics span,.panel span{color:var(--muted);font-size:13px}.metrics strong{display:block;margin-top:10px;font:600 28px var(--font-mono)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.heading,.panel li{display:flex;align-items:center;justify-content:space-between;gap:12px}.panel pre{padding:14px;border-radius:9px;background:var(--canvas);overflow:auto}.panel ul{padding:0;margin:0;list-style:none}.panel li{padding:12px 0;border-bottom:1px solid var(--border)}@media(max-width:800px){.grid{grid-template-columns:1fr}.metrics{grid-template-columns:1fr 1fr}}@media(max-width:480px){.metrics{grid-template-columns:1fr}}</style>
